# NUMPY ASSIGNMENT

In [1]:
import numpy as np

### QUESTION 1


####  A python library is a collection of codes or modules of codes that can be used in a program for specific operations.We use libraries so that we don't 
#### need to write the code again in our program that is already available. Libraries are bundled into packages that you install, which can be imported into your coding environment as needed.
### USES:-
#### 1. Code reusability:- Libraries provide pre-written code that can be reused across projects,saving time and efforts.
#### 2. Functionality:- They offer specialized functions and tools for specific tasks, such as data analysis , machine learning .
#### 3. We can do data manipulation and analysis, offering data structures like DataFrame for working with structured data.

### QUESTION 2

## LIST 
#### It can contain elements of different datatypes.
#### List consumes more memory due to the flexibility of storing different datatypes.
#### List is generally slower for numerical operations.
#### List can be multi-dimensional but handling is intuitive.
#### It is simpler for basic tasks and general purpose program.
## ARRAY
#### In array, all the elements are homogeneous i.e. of same datatype.
#### It is memory efficient as it stores elements in a contiguos block of memory.
#### Array is optimal for numerical operations, making them faster.
#### Array is optimal for numerical operations, making them faster.
#### It is created using the 'numpy.array()'.
#### It is more powerful for numerical and scientific calculations.

#### QUESTION 3

In [2]:
arr1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
np.shape(arr1)

(3, 4)

In [4]:
np.size(arr1)

12

In [5]:
np.ndim(arr1)

2

#### QUESTION 4

In [7]:
arr2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
arr2[0]

array([1, 2, 3, 4])

In [12]:
arr3 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

#### QUESTION 5

In [13]:
arr4 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
arr4[2][3]

12

#### QUESTION 6

In [16]:
arr5 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr5

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
odd_indexed_elements = arr5[:, 1::2].flatten()

print("All odd-indexed elements:", odd_indexed_elements)

All odd-indexed elements: [ 2  4  6  8 10 12]


#### QUESTION 7

In [19]:
random_matrix = np.random.rand(3, 3)

print("Random 3x3 Matrix:")
print(random_matrix)

Random 3x3 Matrix:
[[0.23415345 0.45283785 0.99505535]
 [0.40470368 0.46314994 0.92670307]
 [0.36360297 0.25032723 0.26728733]]


#### QUESTION 8

#### "np.random.rand" generates random numbers from a uniform distribution in interval [0,1).
#### "np.random.randn" generates random numbers from a standard normal distribution (mean = 0 , standard deviation = 1)

#### QUESTION 9

In [20]:
arr6 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr6

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
arr7 = np.expand_dims(arr6,axis=0)
arr7

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

#### QUESTION 10

In [22]:
arr8 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr8

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
arr9 = arr8.T
arr9

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

#### QUESTION 11

In [49]:
matrix_A = np.array([[1,2,3,4],
                   [5,6,7,8],
                  [9,10,11,12]])

matrix_B = np.array([[1,2,3,4],
                    [5,6,7,8],
                   [9,10,11,12]])


In [50]:
# 1. Indexwise multiplication
matrix_A * matrix_B

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [52]:
# 2. Matrix Multiplication 
result_matrix = np.dot(matrix_A , matrix_B)
result_matrix

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [41]:
# 3. Add both the matrices
matrix_A+ matrix_B

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [42]:
# 4. Subtract matrix B from A
matrix_A - matrix_B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [43]:
# 5. Divide matrix B by A
matrix_B / matrix_A

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### QUESTION 12

#### In NumPy, the byteswap function can be used to swap the byte order of an array. This function returns a new array with the byte order swapped. 

#### QUESTION 13

#### The np.linalg.inv function in NumPy is used to compute the (multiplicative) inverse of a square matrix. The significance of finding the inverse of a matrix lies in various mathematical and practical applications. It is used in matrix division , eigen value and eigen vector calculations.

#### QUESTION 14

#### The np.reshape function in NumPy is used to give a new shape to an array without changing the data.It returns a new array with the same data but a different shape. 

#### QUESTION 15

#### Broadcasting is a powerful feature in NumPy that allows arrays of different shapes and sizes to be combined in a way that makes sense for arithmetic operations. In other words, NumPy can automatically perform element-wise operations on arrays of different shapes without explicitly reshaping them.